### PR TITLE
BigFloat compatibility

### LINKED ISSUE #94: BigFloat matrix in partialschur() does not work
MWE:

```
using ArnoldiMethod, LinearAlgebra, SparseArrays
function mwe()
A = spdiagm(
           -1 => -1.0*ones(9),
            0 =>  2.0*ones(10), 
            1 => -1.0*ones(9)
       );
B = spdiagm(
           -1 => -big(1.0)*ones(9),
            0 => big(2.0)*ones(10), 
            1 => -big(1.0)*ones(9)
       );
display(A)
decomp, history = partialschur(A, nev=10, tol=1e-6, which=SR());
display(decomp)

display(B)
decomp, history = partialschur(B, nev=10, tol=1e-6, which=SR());
display(decomp)
end
```

Output:

```

julia> mwe()
10×10 SparseMatrixCSC{Float64,Int64} with 28 stored entries:
  [1 ,  1]  =  2.0
  [2 ,  1]  =  -1.0
  [1 ,  2]  =  -1.0
  [2 ,  2]  =  2.0
  [3 ,  2]  =  -1.0
  [2 ,  3]  =  -1.0
  [3 ,  3]  =  2.0
  [4 ,  3]  =  -1.0
  [3 ,  4]  =  -1.0
  ⋮
  [8 ,  7]  =  -1.0
  [7 ,  8]  =  -1.0
  [8 ,  8]  =  2.0
  [9 ,  8]  =  -1.0
  [8 ,  9]  =  -1.0
  [9 ,  9]  =  2.0
  [10,  9]  =  -1.0
  [9 , 10]  =  -1.0
  [10, 10]  =  2.0
10×10 SparseMatrixCSC{BigFloat,Int64} with 28 stored entries:
  [1 ,  1]  =  2.0
  [2 ,  1]  =  -1.0
  [1 ,  2]  =  -1.0
  [2 ,  2]  =  2.0
  [3 ,  2]  =  -1.0
  [2 ,  3]  =  -1.0
  [3 ,  3]  =  2.0
  [4 ,  3]  =  -1.0
  [3 ,  4]  =  -1.0
  ⋮
  [8 ,  7]  =  -1.0
  [7 ,  8]  =  -1.0
  [8 ,  8]  =  2.0
  [9 ,  8]  =  -1.0
  [8 ,  9]  =  -1.0
  [9 ,  9]  =  2.0
  [10,  9]  =  -1.0
  [9 , 10]  =  -1.0
  [10, 10]  =  2.0
PartialSchur decomposition (Float64) of dimension 10
eigenvalues:
10-element Array{Complex{Float64},1}:
 0.08101405277100668 + 0.0im
 0.31749293433763753 + 0.0im
  0.6902785321094296 + 0.0im
   1.169169973996227 + 0.0im
   1.715370323453429 + 0.0im
   2.284629676546568 + 0.0im
   2.830830026003772 + 0.0im
  3.3097214678905678 + 0.0im
   3.682507065662358 + 0.0im
  3.9189859472289927 + 0.0im
ERROR: MethodError: no method matching gemv!(::Char, ::BigFloat, ::SubArray{BigFloat,2,Array{BigFloat,2},Tuple{Base.Slice{Base.OneTo{Int64}},UnitRange{Int64}},true}, ::SubArray{BigFloat,1,Array{BigFloat,2},Tuple{UnitRange{Int64},Int64},true}, ::BigFloat, ::SubArray{BigFloat,1,Array{BigFloat,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true})
Closest candidates are:
  gemv!(::AbstractChar, ::Float64, ::Union{AbstractArray{Float64,1}, AbstractArray{Float64,2}}, ::AbstractArray{Float64,1}, ::Float64, ::AbstractArray{Float64,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/blas.jl:565
  gemv!(::AbstractChar, ::Float32, ::Union{AbstractArray{Float32,1}, AbstractArray{Float32,2}}, ::AbstractArray{Float32,1}, ::Float32, ::AbstractArray{Float32,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/blas.jl:565
  gemv!(::AbstractChar, ::Complex{Float64}, ::Union{AbstractArray{Complex{Float64},1}, AbstractArray{Complex{Float64},2}}, ::AbstractArray{Complex{Float64},1}, ::Complex{Float64}, ::AbstractArray{Complex{Float64},1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/blas.jl:565

```

### PR DESCRIPTION
**Pull request by fgerick**
This makes the use of "arbitrary" number types available for Julia `>=v1.5` (due to `mul!` interface). This is also why the build fails on `v1.0`, not sure if this is something that needs to be supported.

I've updated also `StaticArrays` and included `SizedArrays` for non-`isbitstype`s in `lu`. I added the tests for many cases, but there are a few missing, as `randn(BigFloat,n,n)` does not yet exist in Julia.

closes #94

### CODE REVIEW

**Comment by haampie** [comment]
Thanks! This is great! `mul!` should be available since julia 1.3, were you hitting problems on 1.3/1.4? I'll test it when I have time

**Comment by fgerick** [comment]
Ah my bad `mul!` was already in 1.3, time flies...  I quickly checked with 1.3.1 and most tests work, just that there seems to be a tiny (`4e-78`) difference in the BigFloat precision:

```julia
Zero eigenvalues & low-rank matrices: Test Failed at /Users/felixger/.julia/dev/ArnoldiMethod/test/partial_schur.jl:24
  Expression: norm(B * schur.Q - schur.Q * schur.R) < 100 * eps(real(T))
   Evaluated: 1.731313276802366659169719086885007092791536617145785506261475248523890470176717e-75 < 1.727233711018888925077270372560079914223200072887256277004740694033718360632485e-75
Stacktrace:
 [1] top-level scope at /Users/felixger/.julia/dev/ArnoldiMethod/test/partial_schur.jl:24
 [2] top-level scope at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107
 [3] top-level scope at /Users/felixger/.julia/dev/ArnoldiMethod/test/partial_schur.jl:13
Test Summary:                        | Pass  Fail  Total
Zero eigenvalues & low-rank matrices |   19     1     20
ERROR: LoadError: LoadError: Some tests did not pass: 19 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/felixger/.julia/dev/ArnoldiMethod/test/partial_schur.jl:6
in expression starting at /Users/felixger/.julia/dev/ArnoldiMethod/test/runtests.jl:16
ERROR: Package ArnoldiMethod errored during testing
```

**Comment by haampie** [comment]
Let's see if those spurious errors persist or not, right now CI is fine.

**Comment by haampie** [comment]
how do i get rid of travis...

**Comment by haampie** [comment]
Thanks for the contribution! A new version is pending.

I can highly recommend `MultiFloats.jl` over BigFloat by the way since it works in-place

**Comment by fgerick** [comment]
Cool! I didn't know about that package, thanks :) I've been using `DoubleFloats.jl` mostly. I'll check out if the advertised 2x performance improvement holds!

**Comment by haampie** [comment]
I think the 2x speedup is mostly due to avoiding the machinery for NaNs

**Pull request merged**
